#! /bin/bash
#install paru
if ! command -v paru &> /dev/null
then
    echo "paru is not installed. Installing paru..."
    (git clone https://aur.archlinux.org/paru.git && cd paru && makepkg -si)
else
    echo "paru is already installed"
fi

paru --sudoloop --needed --noconfirm -S xorg-xkill wl-clipboard sed bluez bluez-tools blueman keyd git base-devel wget fzf bat dex \
neovim firefox qbittorrent steam \
hyprland swww hyprlock xdg-desktop-portal-hyprland waybar polkit-gnome
sudo systemctl enable keyd bluetooth && \
sudo systemctl start keyd bluetooth


#install fonts
paru --sudoloop --needed --noconfirm -S adobe-source-han-sans-cn-fonts adobe-source-han-sans-jp-fonts adobe-source-han-sans-kr-fonts adobe-source-han-sans-otc-fonts adobe-source-han-sans-tw-fonts adobe-source-han-serif-cn-fonts adobe-source-han-serif-jp-fonts adobe-source-han-serif-kr-fonts adobe-source-han-serif-otc-fonts adobe-source-han-serif-tw-fonts \
nerd-fonts \
ttf-font-awesome-5 \
ttf-jetbrains-mono


#kgx to kitty
sudo rm -rf /usr/bin/kgx && sudo ln -sf /usr/bin/kitty /usr/bin/kgx

#nautilus open any terminal here
paru --sudoloop --noconfirm --needed -S nautilus-open-any-terminal
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal kitty

#set default file manager
xdg-mime default org.gnome.Nautilus.desktop inode/directory

#gdm enable wayland
sudo sed -i 's/#WaylandEnable=false/WaylandEnable=true/g' /etc/gdm/custom.conf

#enable some nvidia services
sudo systemctl enable nvidia-suspend.service nvidia-hibernate.service nvidia-resume.service
#Note: Add "nvidia_drm.modeset=1 nvidia.NVreg_PreserveVideoMemoryAllocations=1" kernel parameters if gdm does not show wayland options.
