#! /bin/bash
sudo pacman --needed --noconfirm -S bluez bluez-tools keyd neovim firefox git base-devel wget fzf bat qbittorrent steam \
hyprland hyprpaper hyprlock xdg-desktop-portal-hyprland waybar \
&& \
sudo systemctl enable keyd bluetooth && \
sudo systemctl start keyd bluetooth
#install fonts
sudo pacman --needed --noconfirm -S adobe-source-han-sans-cn-fonts adobe-source-han-sans-jp-fonts adobe-source-han-sans-kr-fonts adobe-source-han-sans-otc-fonts adobe-source-han-sans-tw-fonts adobe-source-han-serif-cn-fonts adobe-source-han-serif-jp-fonts adobe-source-han-serif-kr-fonts adobe-source-han-serif-otc-fonts adobe-source-han-serif-tw-fonts \
nerd-fonts
if ! command -v paru &> /dev/null
then
    echo "paru is not installed. Installing paru..."
    (git clone https://aur.archlinux.org/paru.git && cd paru && makepkg -si)
else
    echo "paru is already installed"
fi
#kgx to kitty
sudo rm -rf /usr/bin/kgx && sudo ln -sf /usr/bin/kitty /usr/bin/kgx
#set default file manager
xdg-mime default org.gnome.Nautilus.desktop inode/directory
