#! /bin/bash
#install paru
if ! command -v paru &> /dev/null
then
    echo "paru is not installed. Installing paru..."
    (git clone https://aur.archlinux.org/paru.git && cd paru && makepkg -si)
else
    echo "paru is already installed"
fi



sudo pacman --noconfirm -Syu
paru --sudoloop --noconfirm -Syu
paru --sudoloop --needed --noconfirm -S xorg-xkill wl-clipboard sed bluez bluez-tools blueman keyd git base-devel wget fzf bat dex fish \
neovim firefox qbittorrent steam \
hyprland swww hyprlock xdg-desktop-portal-hyprland waybar polkit-gnome \
networkmanager network-manager-applet
sudo systemctl enable keyd bluetooth && \
sudo systemctl start keyd bluetooth

#install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
echo '. "$HOME/.cargo/env"' | /bin/bash
echo 'source "$HOME/.cargo/env"' | fish


#install fonts
paru --sudoloop --needed --noconfirm -S  noto-fonts-cjk noto-fonts-emoji noto-fonts ttf-freefont ttf-ms-fonts ttf-linux-libertine ttf-dejavu ttf-inconsolata ttf-ubuntu-font-family \
nerd-fonts \
ttf-font-awesome-5 \
ttf-jetbrains-mono


#kgx to kitty
sudo rm -rf /usr/bin/kgx && sudo ln -sf /usr/bin/kitty /usr/bin/kgx

#nautilus open any terminal here
paru --sudoloop --noconfirm --needed -S nautilus-open-any-terminal
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal kitty

#set default file manager
xdg-mime default org.gnome.Nautilus.desktop inode/directory

#gdm enable wayland
sudo sed -i 's/#WaylandEnable=false/WaylandEnable=true/g' /etc/gdm/custom.conf

#enable some nvidia services
sudo systemctl enable nvidia-suspend.service nvidia-hibernate.service nvidia-resume.service
#Note: Add "nvidia_drm.modeset=1 nvidia.NVreg_PreserveVideoMemoryAllocations=1" kernel parameters if gdm does not show wayland options.
